return map:new({width = 50,name = "test map",file = "m1",height = 50,{},
{},
{[10] = tile:new({item = items.i2,}),},
{[3] = tiles.t2:new({}),[4] = tiles.t2:new({}),[5] = tiles.t2:new({}),[6] = tiles.t1:new({}),[7] = tiles.t2:new({}),[8] = tiles.t2:new({}),[9] = tiles.t2:new({}),},
{[3] = tiles.t2:new({}),[4] = tiles.t1:new({}),[5] = tiles.t1:new({}),[6] = tiles.t1:new({}),[7] = tiles.t1:new({}),[8] = tiles.t1:new({}),[9] = tiles.t2:new({}),},
{[3] = tiles.t2:new({}),[4] = tiles.t1:new({object = objects.o1}),[5] = tiles.t1:new({}),[6] = tiles.t1:new({}),[7] = tiles.t1:new({}),[8] = tiles.t1:new({}),[9] = tiles.t2:new({}),[10] = tile:new({item = items.i1,}),},
{[3] = tiles.t2:new({}),[4] = tiles.t1:new({object = objects.o1}),[5] = tiles.t1:new({}),[6] = tiles.t2:new({item = items.i1,}),[7] = tiles.t1:new({}),[8] = tiles.t1:new({}),[9] = tiles.t2:new({}),[10] = tile:new({item = items.i1,}),},
{[3] = tiles.t2:new({}),[4] = tiles.t1:new({object = objects.o1}),[5] = tiles.t1:new({}),[6] = tiles.t2:new({item = items.i1,}),[7] = tiles.t1:new({}),[8] = tiles.t1:new({}),[9] = tiles.t2:new({}),[10] = tile:new({item = items.i1,}),},
{[3] = tiles.t2:new({}),[4] = tiles.t1:new({object = objects.o1}),[5] = tiles.t1:new({}),[6] = tiles.t1:new({}),[7] = tiles.t1:new({}),[8] = tiles.t1:new({}),[9] = tiles.t2:new({}),[10] = tile:new({item = items.i1,}),},
{[3] = tiles.t2:new({}),[4] = tiles.t1:new({}),[5] = tiles.t1:new({}),[6] = tiles.t1:new({}),[7] = tiles.t1:new({}),[8] = tiles.t1:new({}),[9] = tiles.t2:new({}),[10] = tile:new({item = items.i1,}),},
{[3] = tiles.t2:new({}),[4] = tiles.t2:new({}),[5] = tiles.t2:new({}),[6] = tiles.t2:new({}),[7] = tiles.t2:new({}),[8] = tiles.t2:new({}),[9] = tiles.t2:new({}),},
{[5] = tile:new({item = items.i2,}),[6] = tile:new({item = items.i2,}),[7] = tile:new({item = items.i2,}),},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
players = {npcs.n1:new({x = 2,y = 10}),},
spawn = {x = 10,y = 6}})