return map:new({width = 50,file = "m1",name = "test map",height = 50,{},
{},
{},
{[3] = tiles.t2:new(),[4] = tiles.t2:new(),[5] = tiles.t2:new(),[6] = tiles.t1:new(),[7] = tiles.t2:new(),[8] = tiles.t2:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t1:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t1:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t2:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t2:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t1:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t1:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t2:new(),[5] = tiles.t2:new(),[6] = tiles.t2:new(),[7] = tiles.t2:new(),[8] = tiles.t2:new(),[9] = tiles.t2:new(),},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
spawn = {x = 10,y = 6}})