return map:new({width = 50,height = 50, file = "m1", {},
{},
{},
{[3] = tiles.t2:new(),[4] = tiles.t2:new(),[5] = tiles.t2:new(),[6] = tiles.t1:new(),[7] = tiles.t2:new(),[8] = tiles.t2:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t1:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t1:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t1:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t1:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t1:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t1:new(),[5] = tiles.t1:new(),[6] = tiles.t1:new(),[7] = tiles.t1:new(),[8] = tiles.t1:new(),[9] = tiles.t2:new(),},
{[3] = tiles.t2:new(),[4] = tiles.t2:new(),[5] = tiles.t2:new(),[6] = tiles.t2:new(),[7] = tiles.t2:new(),[8] = tiles.t2:new(),[9] = tiles.t2:new(),},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
{},
name = "text map"})